const dbConfig = require('../../config/db.config.js');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.webmd = require('./Webmd.js')(mongoose);
db.wowcount = require('./WowCount.js')(mongoose);
module.exports = db;
